### ISSUE TITLE
LLMMap does not correctly return values from the option list input.

### ISSUE THREAD

**Issue by ZhaoFuheng** [parkervg/blendsql#31]
**Describe the bug**
First of all, thank you for this amazing project.
I'm running some experiments with BlendSQL. There seems to be some weird behaviour with LLMMap in which the options field are not correct populated?

**To Reproduce**
Here is a BlendSQL statement I used:
```SELECT *
FROM frpm
WHERE {{ LLMMap(
        'What is the educational option type?',
        'frpm::School Name',
        options='Traditional;Juvenile Court School;County Community School;State Special School;Alternative School of Choice;Continuation School;Special Education School;Community Day School;Home and Hospital;Opportunity School;Youth Authority School;District Special Education Consortia School'
        )
}} = 'Continuation School'```

Here is the meta output:
{'answer': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'], 'question': 'What is the educational option type?', 'values': ['Academy of Careers and Exploration', 'ASA Charter', 'Adelanto High', 'Academy for Academic Excellence', 'Allen (Ella B.) Elementary', 'Academy of Arts and Sciences: El Cajon Middle and High (6-12)', 'Academy of Arts and Sciences: Del Mar Elementary (K-5)', 'Academy of Arts and Sciences: Del Mar Middle & High (6-12)', 'Abraxas Continuation High', 'Adobe Bluffs Elementary', 'Albert Einstein Academy Charter Middle', 'Alamosa Park Elementary', 'All Tribes Charter', 'Academy of Arts and Sciences', 'Acacia Middle Charter']}


**Expected behavior**
I expected that the answer should be a list of values selected from the options.



**Desktop (please complete the following information):**
 Python 3.9 on MacOS

**Comment by parkervg** [comment]
Hi @ZhaoFuheng! Thank you for your interest in this project. 

If you have time, could you also provide the code you used to initialize the LLM being passed to the `blend` function? This will help me debug. For example, local Transformer models are handled differently than remote OpenAI endpoints.

For the `LLMMap` behavior you're seeing, the codebase uses the `-` character as effectively a `null` answer throughout ingredients. The reason for this is we wanted a way for a given model to opt-out of answering a question given an irrelevant input. Taking the following code as an example:

```python
from blendsql.db import Pandas 

# Prepare our local database
db = Pandas(
  {
    "frpm": pd.DataFrame(
      (
        ['Los Altos High School'],
        ['Boston Career Institute'],
        ['Juvenile Court School'],
        ['this is not a school']
      ),
      columns=['School Name']
    )
  }
)

blendsql = """
SELECT {{
    LLMMap(
        'What school type?',
        'frpm::School Name',
        options='Traditional;Juvenile Court School;County Community School;State Special School;Alternative School of Choice;Continuation School;Special Education School;Community Day School;Home and Hospital;Opportunity School;Youth Authority School;District Special Education Consortia School'
    )
}} FROM frpm
"""
```

When executing the question `What school type?'` against each of the values in the database, `this is not a school` shouldn't really satisfy any SQL predicate using the output of the `LLMMap` function, since it's not a school. Therefore, we add the `-` value as a catch-all for instances where we need a sort of `null` response.

That being said - I'm finishing up a change now that will allow you to change this default behavior for your usecase! I will let you know when it's pushed.

**Comment by parkervg** [comment]
Pushed! After installing from main with `pip install git+https://github.com/parkervg/blendsql`, you now can initialize your LLMMap ingredient like below:

```python
LLMMap.from_args(allow_null_option=False)
```

This will remove the null option `-` from being included in the regular expression that guides the language model generation.

I'm planning on cleaning up the LLM prompting portion of this library to increase interpretability + control over situations like these. Let me know if anything else would be useful for your experiments and I can prioritize those!

**Comment by ZhaoFuheng** [comment]
Thank you so much for your quick response. 

I used the OpenAI model  "gpt-3.5-turbo" and config={"temperature": 0}.
    
There also seems to be an issue with the behavior around NULL values.

The table looks like:
Pandas(
  {
    "frpm": pd.DataFrame(
      [[194.0, 244.0, 'ARISE High'], [354.0, 433.0, 'ASCEND'], [318.0, 373.0, 'A. L. Conner Elementary'], [698.0, 1014.0, 'Abraham Lincoln Middle'], [93.0, 254.0, 'Academies of the Antelope Valley'], [400.0, 463.0, 'Academia Moderna'], [82.0, 723.0, 'Acacia Elementary'], [208.0, 370.0, 'A. J. Cook Elementary'], [64.0, 618.0, 'Abraham Lincoln Elementary'], [518.0, 631.0, 'Abraham Lincoln Elementary'], [155.0, 215.0, 'ASA Charter'], [26.0, 94.0, 'Abraxas Continuation High'], [65.0, 74.0, 'Acacia Middle Charter'], [216.0, 264.0, 'Acacia Elementary Charter'], [275.0, 802.0, 'Abbott Middle'], [346.0, 404.0, 'ACE Empower Academy'], [63.0, 71.0, 'ACE Alum Rock'], [211.0, 219.0, 'ACE Charter High'], [134.0, 149.0, 'ACE Franklin McKinley'], [47.0, 57.0, 'Academic/Vocational Charter Institute']],
      columns=['Free Meal Count (Ages 5-17)', 'Enrollment (Ages 5-17)', 'School Name']
    )
  }
)

In the query a predicate on `Free Meal Count (Ages 5-17)` / `Enrollment (Ages 5-17)` IS NOT NULL.
However, in the meta data field the value list is empty. 
When I removed this NOT NULL predicate everything seem to be working.

The query is 
   ```SELECT COUNT(*) FROM frpm
WHERE `Free Meal Count (Ages 5-17)` / `Enrollment (Ages 5-17)` IS NOT NULL
AND {{
    LLMMap(
         'Is the educational option type of the following school Traditional?',
        'frpm::School Name'
    )
}} = TRUE
ORDER BY `Free Meal Count (Ages 5-17)` / `Enrollment (Ages 5-17)` ASC
LIMIT 10

**Comment by ZhaoFuheng** [comment]
I would also love to see some examples of how to incorporate few-shot demonstrations in BlendSQL.
What is the best practice to add few-shot in LLMMap and LLMQA?

**Comment by parkervg** [comment]
Got it! After the most recent change, running this query with `LLMMap.from_args(allow_null_option=False)` and gpt-3.5-turbo: 
```python
SELECT frpm."School Name", {{
    LLMMap(
        'What school type?',
        'frpm::School Name',
        options='Traditional;Juvenile Court School;County Community School;State Special School;Alternative School of Choice;Continuation School;Special Education School;Community Day School;Home and Hospital;Opportunity School;Youth Authority School;District Special Education Consortia School'
    )
}} AS "Classification" FROM frpm
```
Returns (i.e. `print(smoothie.df)`): 

| School Name                           | Classification               |
|:--------------------------------------|:-----------------------------|
| ARISE High                            | Alternative School of Choice |
| ASCEND                                | Alternative School of Choice |
| A. L. Conner Elementary               | Traditional                  |
| Abraham Lincoln Middle                | Traditional                  |
| Academies of the Antelope Valley      | Traditional                  |
| Academia Moderna                      | Traditional                  |
| Acacia Elementary                     | Traditional                  |
| A. J. Cook Elementary                 | Traditional                  |
| Abraham Lincoln Elementary            | Traditional                  |
| Abraham Lincoln Elementary            | Traditional                  |
| ASA Charter                           | Alternative School of Choice |
| Abraxas Continuation High             | Continuation School          |
| Acacia Middle Charter                 | Alternative School of Choice |
| Acacia Elementary Charter             | Traditional                  |
| Abbott Middle                         | Traditional                  |
| ACE Empower Academy                   | Traditional                  |
| ACE Alum Rock                         | Alternative School of Choice |
| ACE Charter High                      | Traditional                  |
| ACE Franklin McKinley                 | Alternative School of Choice |
| Academic/Vocational Charter Institute | Alternative School of Choice |

I will look into the `NOT NULL` case in greater detail later. 

Few-shot demonstrations is definitely an area I'd like to improve on in this codebase! Currently it's pretty hard-coded to fit the datasets we studied in our paper, but this can definitely be improved. I have some free time these next couple weeks, this will definitely be one of my activities 😊

**Comment by parkervg** [comment]
As a possible solution, you could also achieve finer control over the language model prompts by subclassing the `MapIngredient` class and creating your own custom function, as described here: https://parkervg.github.io/blendsql/reference/ingredients/creating-custom-ingredients/ 

Documentation is lacking, but essentially you can do something like this:

```python
from typing import List
import random
from blendsql.ingredients import MapIngredient

class CustomMap(MapIngredient):
    def run(self, values: List[str], options: List[str] = None, **_):
        mapped_values = []
        # Logic for prompting + generating mapped_values goes here
        for value in values:
            mapped_values.append(random.choice(options))
        assert len(mapped_values) == len(values)
        return mapped_values

ingredients={CustomMap.from_args(allow_null_option=False)}
```

By virtue of subclassing `MapIngredient`, there are a number of arguments that get passed to the `run()` function. Here, we capture all the irrelevant ones in `**_`, but for a full list you can check out the `LLMMap` class in the codebase, under `ingredients/map/main.py`
